name: riverpod_community_mutation
description: A mutation implementation for the riverpod community - made by Theodo
version: 1.0.1
homepage: https://github.com/bamlab/riverpod_community_mutation
repository: https://github.com/bamlab/riverpod_community_mutation

environment:
  sdk: ^3.5.0

dependencies:
  riverpod: ^2.6.1
